version: '2.3'

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
    user: '1000'

services:
  commons:
    image: uselagoon/commons:latest
    << : *default-user # uses the defined user from top

  mariadb-10-4:
    image: uselagoon/mariadb-10.4:latest
    ports:
      - "3306"
    << : *default-user # uses the defined user from top

  mariadb-10-5:
    image: uselagoon/mariadb-10.5:latest
    ports:
      - "3306"
    << : *default-user # uses the defined user from top

  mariadb-10-6:
    image: uselagoon/mariadb-10.6:latest
    ports:
      - "3306"
    << : *default-user # uses the defined user from top

  mariadb-10-11:
    image: uselagoon/mariadb-10.11:latest
    ports:
      - "3306"
    << : *default-user # uses the defined user from top

  mongo-4:
    image: uselagoon/mongo-4:latest
    ports:
      - "27017"
      - "28017"
    << : *default-user # uses the defined user from top

  nginx:
    image: uselagoon/nginx:latest
    labels:
      lando.type: nginx
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker-compose port nginx 8080`
    << : *default-user # uses the defined user from top

  node-16:
    image: uselagoon/node-16:latest
    ports:
      - "3000"
    user: root
    command: ["sh", "-c", "
        npm install -g http-server;
        node -v | xargs > /app/test.html;
        exec http-server -p 3000
        "]

  node-18:
    image: uselagoon/node-18:latest
    ports:
      - "3000"
    user: root
    command: ["sh", "-c", "
        npm install -g http-server;
        node -v | xargs > /app/test.html;
        exec http-server -p 3000
        "]

  node-20:
    image: uselagoon/node-20:latest
    ports:
      - "3000"
    user: root
    command: ["sh", "-c", "
        npm install -g http-server;
        node -v | xargs > /app/test.html;
        exec http-server -p 3000
        "]

  postgres-11:
    image: uselagoon/postgres-11:latest
    ports:
      - "5432"
    << : *default-user # uses the defined user from top

  postgres-12:
    image: uselagoon/postgres-12:latest
    ports:
      - "5432"
    << : *default-user # uses the defined user from top

  postgres-13:
    image: uselagoon/postgres-13:latest
    ports:
      - "5432"
    << : *default-user # uses the defined user from top

  postgres-14:
    image: uselagoon/postgres-14:latest
    ports:
      - "5432"
    << : *default-user # uses the defined user from top

  postgres-15:
    image: uselagoon/postgres-15:latest
    ports:
      - "5432"
    << : *default-user # uses the defined user from top

  php-8-0-dev:
    image: uselagoon/php-8.0-cli:latest
    ports:
      - "9000"
    environment:
      - LAGOON_ENVIRONMENT_TYPE=development
      - XDEBUG_ENABLE=true
      - XDEBUG_LOG=true
      - NEWRELIC_ENABLED=true
      - BLACKFIRE_ENABLED=true
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        echo PD9waHAKCnBocGluZm8oICk7Cgo/Pg== | base64 -d > /app/index.php;
        exec php -S 0.0.0.0:9000
        "] # runs a webserver with phpinfo output

  php-8-0-prod:
    image: uselagoon/php-8.0-cli:latest
    ports:
      - "9000"
    environment:
      - LAGOON_ENVIRONMENT_TYPE=production
      - PHP_MAX_INPUT_VARS=4000
      - PHP_MAX_FILE_UPLOADS=40
      - PHP_SESSION_COOKIE_SAMESITE="Strict"
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        echo PD9waHAKCnBocGluZm8oICk7Cgo/Pg== | base64 -d > /app/index.php;
        exec php -S 0.0.0.0:9000
        "] # runs a webserver with phpinfo output

  php-8-1-dev:
    image: uselagoon/php-8.1-cli:latest
    ports:
      - "9000"
    environment:
      - LAGOON_ENVIRONMENT_TYPE=development
      - XDEBUG_ENABLE=true
      - XDEBUG_LOG=true
      - NEWRELIC_ENABLED=true
      - BLACKFIRE_ENABLED=true
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        echo PD9waHAKCnBocGluZm8oICk7Cgo/Pg== | base64 -d > /app/index.php;
        exec php -S 0.0.0.0:9000
        "] # runs a webserver with phpinfo output

  php-8-1-prod:
    image: uselagoon/php-8.1-cli:latest
    ports:
      - "9000"
    environment:
      - LAGOON_ENVIRONMENT_TYPE=production
      - PHP_MAX_INPUT_VARS=4000
      - PHP_MAX_FILE_UPLOADS=40
      - PHP_SESSION_COOKIE_SAMESITE="Strict"
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        echo PD9waHAKCnBocGluZm8oICk7Cgo/Pg== | base64 -d > /app/index.php;
        exec php -S 0.0.0.0:9000
        "] # runs a webserver with phpinfo output

  php-8-2-dev:
    image: uselagoon/php-8.2-cli:latest
    ports:
      - "9000"
    environment:
      - LAGOON_ENVIRONMENT_TYPE=development
      - XDEBUG_ENABLE=true
      - XDEBUG_LOG=true
      - NEWRELIC_ENABLED=true
      - BLACKFIRE_ENABLED=true
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        echo PD9waHAKCnBocGluZm8oICk7Cgo/Pg== | base64 -d > /app/index.php;
        exec php -S 0.0.0.0:9000
        "] # runs a webserver with phpinfo output

  php-8-2-prod:
    image: uselagoon/php-8.2-cli:latest
    ports:
      - "9000"
    environment:
      - LAGOON_ENVIRONMENT_TYPE=production
      - PHP_MAX_INPUT_VARS=4000
      - PHP_MAX_FILE_UPLOADS=40
      - PHP_SESSION_COOKIE_SAMESITE="Strict"
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        echo PD9waHAKCnBocGluZm8oICk7Cgo/Pg== | base64 -d > /app/index.php;
        exec php -S 0.0.0.0:9000
        "] # runs a webserver with phpinfo output

  python-3-7:
    image: uselagoon/python-3.7:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        python -V | xargs > tmp/test;
        exec python -m http.server 3000
        "]

  python-3-8:
    image: uselagoon/python-3.8:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        python -V | xargs > tmp/test;
        exec python -m http.server 3000
        "]

  python-3-9:
    image: uselagoon/python-3.9:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        python -V | xargs > tmp/test;
        exec python -m http.server 3000
        "]

  python-3-10:
    image: uselagoon/python-3.10:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        python -V | xargs > tmp/test;
        exec python -m http.server 3000
        "]

  python-3-11:
    image: uselagoon/python-3.11:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        python -V | xargs > tmp/test;
        exec python -m http.server 3000
        "]

  rabbitmq:
    image: uselagoon/rabbitmq:latest
    ports:
      - "5672"
      - "15672"
    << : *default-user # uses the defined user from top

  redis-5:
    image: uselagoon/redis-5:latest
    ports:
      - "6379"
    << : *default-user # uses the defined user from top

  redis-6:
    image: uselagoon/redis-6:latest
    ports:
      - "6379"
    << : *default-user # uses the defined user from top

  redis-7:
    image: uselagoon/redis-7:latest
    ports:
      - "6379"
    << : *default-user # uses the defined user from top

  solr-7:
    image: uselagoon/solr-7:latest
    ports:
      - "8983"
    << : *default-user # uses the defined user from top

  solr-8:
    image: uselagoon/solr-8:latest
    ports:
      - "8983"
    user: solr

  ruby-3-0:
    image: uselagoon/ruby-3.0:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        ruby -v | xargs > /tmp/index.html;
        exec ruby -run -e httpd / -p 3000
        "]

  ruby-3-1:
    image: uselagoon/ruby-3.1:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        ruby -v | xargs > /tmp/index.html;
        exec ruby -run -e httpd / -p 3000
        "]

  ruby-3-2:
    image: uselagoon/ruby-3.2:latest
    ports:
      - "3000"
    << : *default-user # uses the defined user from top
    command: ["sh", "-c", "
        ruby -v | xargs > /tmp/index.html;
        exec ruby -run -e httpd / -p 3000
        "]

  varnish-6:
    image: uselagoon/varnish-6:latest
    labels:
      lando.type: varnish
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker-compose port varnish-6 8080`
    << : *default-user # uses the defined user from top
    depends_on:
      - nginx

  varnish-7:
    image: uselagoon/varnish-7:latest
    labels:
      lando.type: varnish
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker-compose port varnish-7 8080`
    << : *default-user # uses the defined user from top
    depends_on:
      - nginx

  opensearch-2:
    image: uselagoon/opensearch-2:latest
    labels:
      lando.type: opensearch
    ports:
      - "9200" # exposes the port 8080 with a random local port, find it with `docker-compose port nginx 8080`
    << : *default-user # uses the defined user from top

  internal-services-test:
    image: docker.io/uselagoon/internal-services-test:main
    ports:
      - "3000"
    environment:
      - LAGOON_TEST_VAR=all-images
    << : *default-user # uses the defined user from top
