kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind
  commands:
  - apk add --no-cache build-base bash
  - make -Otarget -j8 build
  - docker image ls
  volumes:
  - name: dockersock
    path: /var/run/docker.sock

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock