kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:19.03-git
  commands:
  - apk add --no-cache build-base
  - make -Otarget -j8 build
  - docker image ls
  volumes:
  - name: docker
    path: /usr/bin/docker
  - name: docker.sock
    path: /var/run/docker.sock